version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Edge port
      - "4571:4571" # Lambda port
    environment:
      - SERVICES=lambda,apigateway,logs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/emilshalamberidze/localstack_data:/var/lib/localstack/data"
